-- CreateEnum
CREATE TYPE "NOTIFICATION_TYPE" AS ENUM ('TAP', 'BONUS', 'REWARD', 'CARD');

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "type" "NOTIFICATION_TYPE" NOT NULL DEFAULT 'REWARD';
