-- AlterTable
ALTER TABLE "Bonus" ALTER COLUMN "imageUrl" DROP NOT NULL;

-- AlterTable
ALTER TABLE "UserCard" ALTER COLUMN "visitCount" SET DEFAULT 0,
ALTER COLUMN "ownedAt" SET DEFAULT CURRENT_TIMESTAMP;
